---
- name: create error log and set permissions
  file: path={{django_environment.ERROR_LOG_FILE}} owner={{project_name}} group={{project_name}} mode="u=rw,g=r,o=r" state=touch
- name: migrate django project
  become: yes
  become_user: emailcongress
  django_manage: >
    command=migrate
    app_path=/projects/{{project_name}}/src/{{project_name}}
    settings={{django_settings_module}}
    virtualenv=/projects/{{project_name}}/virt
  environment: "{{django_environment}}"
  tags:
    - migrate

# override default nginx template
- name: write nginx template
  template: src=nginx.j2 dest=/etc/nginx/sites-enabled/{{project_name}}
  notify:
    - restart nginx

#  project setup code is handled by common-roles/django-base
- name: ensure nginx is running and starts on boot
  service: name=nginx state=restarted enabled=yes

- name: collect static files
  become: yes
  become_user: emailcongress
  django_manage: >
    command=collectstatic
    app_path=/projects/{{project_name}}/src/{{project_name}}
    virtualenv=/projects/{{project_name}}/virt
  environment: "{{django_environment}}"
