---
- name: Set up emailcongress.us
  hosts: emailcongress-site
  become: yes
  vars:
    configure_user: yes
    hostname: "{{project_name}}.us"
  roles:
    - role: common-roles/common
      when: standalone
      extra_packages:
        - libpq-dev # Need this for psycopg2
        - memcached
    - role: common-roles/node
      npm_packages:
        - yuglify
        - uglify-js
    - role: common-roles/ruby
      gem_packages:
        - sass
    - role: common-roles/django
      python_version: 3
      git_repositories:
        - repo: https://github.com/sunlightlabs/emailcongress.git
          dir: emailcongress
          version: HEAD
      wsgi_module: emailcongress.wsgi:application
      serve_static: yes
    - role: roles/emailcongress
