---
- name: Set up taskqueue.emailcongress
  hosts: emailcongress-taskqueue
  become: yes
  vars:
    concurrency: 2
    worker_nodes: 4
    celeryd_max_tasks_per_child: 500
    proxy_ip: 0.0.0.0
    proxy_port: 3000
    hostname: "taskqueue.{{project_name}}.us"
  roles:
    - role: common-roles/common
      extra_packages:
        - libpq-dev
        - curl
        - ruby-full
    - role: common-roles/redis-server
      bind_external: true
    - role: common-roles/django-celery
      python_version: 3
      celerybeat_enabled: no
      git_repositories:
        - repo: https://github.com/crdunwel/emailcongress.git
          dir: emailcongress
          version: HEAD
    - role: rvm1-ansible
      rvm1_rubies:
        - 'ruby-2.2.0'
      rvm1_install_path: '/projects/{{project_name}}/rvm'
      rvm1_user: '{{project_name}}'
      rvm1_ruby_install_flags: '--autolibs=0' # waits for user input otherwise
    - role: roles/phantom-of-the-capitol
      project_path: /projects/{{project_name}}/src/phantom-of-the-capitol
      dbname: 'phantom_dc'
      dbuser: 'phantom_dc'
      dbpassword: 'test'
      rack_env: 'production'
      git_repositories:
        - repo: https://github.com/EFForg/phantom-of-the-capitol.git
          dir: phantom-of-the-capitol
          version: HEAD
    - role: common-roles/nginx
      http_proxy_pass: yes
